# .github/workflows/rosti_deploy.yml

name: Deploy into Roští.cz

on:
    push:
      branches: [main]

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        HOST: ssh.rosti.cz
        USER: app
        PORT: 26494
        NODE_VERSION: 19.6.0
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "v19.6.0"
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ROSTI_SSH_KEY }}
      - name: Setup hostkey
        run: |
          echo "ssh.rosti.cz ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCSerImj1S/90WjTvUuVW3Pm0D+tFCenD9svYi+4pdo4E1vuJ1W7ikonJfAQbfEEIPVm3OsjUrZEB8Akgx+aqUY/lwpbll7W37IgZTOV7lYNOHMwSZVknLYXj5y3JWgFjOPiljBrZCFFRGc6q2LCZu30U4OjUmLI/uxEM3fULX1CYBg/m+wFGASSZ6SmoLMV9G6BzcmmTpHff1VeHtkMT3Pcz2z95kPQaXlvarFe7892KikqEjLtCS9qLWhEOiBvsLbw+Bqry9sKiP4DD/2uEkKhTvVWlIfbPJ6HJo3i3nwnxPSprB1AbCGQJnY1Z92dKirRB/0yghox0TJDTx12m4v" > ./known_hosts
      - name: Dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
          ./node_modules/.bin/next export
      - name: Setup Nginx
        run: |
          cat << EOF > rosti.nginx.conf
          server {
            listen 8000;

            root /srv/app/;
            index index.html;

            location / {
              try_files $uri $uri/ =404;
            }
          }        
          EOF
          scp -o UserKnownHostsFile=./known_hosts -P $PORT rosti.nginx.conf $USER@$HOST:/srv/conf/nginx.d/app.conf
          rm rosti.nginx.conf
      - name: Copy generated page
        run: |
          rsync -ave "ssh -o UserKnownHostsFile=./known_hosts -p $PORT" --delete-after --exclude=.git ./ $USER@$HOST:/srv/app/
